parameters:
#    acme_my_history.example.class: Acme\MyHistoryBundle\Example

services:
#    acme_my_history.example:
#        class: %acme_my_history.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
